title: 'Double Fire Extinguisher Box'
updated_by: b1671d61-d80a-4045-93e3-2b5d3fa2d941
updated_at: 1631522236
blueprint: sortable_category
localizations:
  germany:
    title: 'Doppelter Feuerlöscherkasten'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631190486
  france:
    title: Double
    updated_by: 6f380b3d-901c-48c0-ad5c-495e8a13ba14
    updated_at: 1631534958
  spain:
    title: 'Caja de Extintor Doble'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1632382833
