title: 'Front Loading Fire'
updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
updated_at: 1631188780
blueprint: sortable_category
localizations:
  france:
    title: 'Chargement Frontal Incendie'
    updated_by: 6f380b3d-901c-48c0-ad5c-495e8a13ba14
    updated_at: 1631176246
  spain:
    title: 'Cajas para Extintores de Carga Frontal'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631188769
  germany:
    title: 'Fronlader - Feuer'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631190461
