title: 'Front Loading'
updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
updated_at: 1631267066
blueprint: sortable_category
localizations:
  germany:
    title: Frontlader
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631267075
  france:
    title: 'Chargement Frontal'
    updated_by: 6f380b3d-901c-48c0-ad5c-495e8a13ba14
    updated_at: 1631173856
  spain:
    title: 'Carga Frontal'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631188505
sort_order: 3
