title: 'Top Loading Safety'
updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
updated_at: 1631188856
blueprint: sortable_category
localizations:
  germany:
    title: 'Toplader - Sicherheit'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631190452
  france:
    title: 'Chargement Par Le Dessus Sécurité'
    updated_by: 6f380b3d-901c-48c0-ad5c-495e8a13ba14
    updated_at: 1631176287
  spain:
    title: 'Cajas de Seguridad de Carga Superior'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631188844
