title: 'Top Loading'
updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
updated_at: 1631267197
blueprint: sortable_category
localizations:
  germany:
    title: 'Beladung von oben'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631267179
  france:
    title: 'Chargement Par Le Dessus'
    updated_by: 6f380b3d-901c-48c0-ad5c-495e8a13ba14
    updated_at: 1631173986
  spain:
    title: 'Carga Superior'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631188547
sort_order: 2
