title: 'Top Loading Fire'
updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
updated_at: 1631188812
blueprint: sortable_category
localizations:
  germany:
    title: 'Toplader - Feuer'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631190442
  france:
    title: 'Chargement Par Le Dessus Incendie'
    updated_by: 6f380b3d-901c-48c0-ad5c-495e8a13ba14
    updated_at: 1631176270
  spain:
    title: 'Cajas para Extintores de Carga Superior'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631188801
