title: 'Fire Extinguisher Boxes'
updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
updated_at: 1632151959
blueprint: sub_categories
image: sub-categories/Category_Thumbnail_500x300-fire-extinguisher-boxes.jpg
sjj: 1
localizations:
  germany:
    title: Feuerlöscherkästen
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631190288
  france:
    title: 'Coffres Extincteur'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631128947
  spain:
    title: 'Cajas para Extintores'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1632319102
