title: Unallocated
updated_by: b1671d61-d80a-4045-93e3-2b5d3fa2d941
updated_at: 1631005435
blueprint: sub_categories
localizations:
  spain:
    title: 'Delete - Unallocated'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631186568
