title: 'Vehicle Fire & Safety Boxes'
updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
updated_at: 1632152083
blueprint: sub_categories
image: sub-categories/Category_Thumbnail_500x300-cv-fire-safety.jpg
sjj: 7
localizations:
  germany:
    title: 'Nutzfarhzeug Brandschutz- & Sicherheitskästen'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631190278
  france:
    title: 'Coffres Extincteur Véhicules'
    updated_by: 6f380b3d-901c-48c0-ad5c-495e8a13ba14
    updated_at: 1631172633
  spain:
    title: 'Cajas para Vehiculos (Incendios y Seguridad)'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1632820537
