title: 'Vehicle Safety Boxes'
updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
updated_at: 1632152077
blueprint: sub_categories
image: sub-categories/vehicle-safety-boxes.jpg
sjj: 9
localizations:
  germany:
    title: 'Nutzfahrzeug Sicherheitskästen'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1631190271
  france:
    title: 'Coffres Sécurité'
    updated_by: 6f380b3d-901c-48c0-ad5c-495e8a13ba14
    updated_at: 1631172543
  spain:
    title: 'Cajas de Seguridad'
    updated_by: 3ec554c2-e8cb-4f28-af79-effcd537d274
    updated_at: 1632311517
