title: Products
sites:
  - english
  - usa
  - france
  - germany
  - spain
template: default
layout: layout
taxonomies:
  - products
  - sub_categories
  - sortable_category
  - parent_category
revisions: false
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
